### ISSUE TITLE
Can kube-throttler solve thundering herd problem (aka  stampede problem)

### ISSUE THREAD

**Issue by buckleyGI** [everpeace/kube-throttler#57]
I came across kube-throttler when looking for a solution to our pressing problem (still not solved) when we bring back a great number of pods after a blackout period.

Let me try to explain our situation. At night we scale all deployments to 0 replicas (and store the original value in an annotation) to reduce costs.
In the morning the replicas are restored to their original values. This is where the problem starts as they overburden the node where the CPU plateaus to 100%.
The warmup probes start to fail and, if they make it, the liveness probes will start restaring the pods. Too many pods are trying to get up at the same time...
After about 2 hours the system finally stabilizes. If we startup the pods manually, say 5 per minute, the system comes up in less then 10 minutes (!).
In other domains this is called the thundering herd problem or stampede problem and we haven't found a fix yet for Kubernetes.

Is this where kube-throttler can help us? I understand that kube-throttler takes into account the CPU utilization but its goal is to be more efficient and not throttle pod creation per se right. Will we be abusing kube-throttler for our use case or is it a good fit you think?

If not it is time for me to learn Go and the Scheduling Framework as it can't be too hard to install a throttle for pod creation on a node where x pods can be created in a sliding window of x minutes. Am I on the right track? Thank you.

**Comment by everpeace** [comment]
_I edited its title to align the issue contents 🙇‍♂️_

**Comment by everpeace** [comment]
I'm closing this due to inactive for long time
